### ISSUE TITLE
Plays tracks way too fast

### ISSUE THREAD

**Issue by dhry** [WilfredC64/sid-device#1]
Have tried Acid64 4.2.1 and also 3.6.3. Running sid-device 1.0. Every track plays at something like 4x normal speed. Using JSIDDevice 4.6, all works fine.

Windows 10 x64.

**Comment by WilfredC64** [comment]
I suspect that the issue is related to some setting of your audio device which might not be handled correctly in sid-device.

Can you please give me more info about your system configuration? Which sound card/device are you using? At what sample rate it is configured to and at how many bits? In Windows you can check the output setting of your audio device and then you have a section with the label 'format' which displays e.g. 16 Bit, 48000 Hz.

Also, can please let me know what audio devices sid-device mentions in the dropdown of the settings dialog (double click on the sid-device icon in the system tray to open the settings dialog)? A screenshot of the expanded dropdown would be nice. If it has more than one audio device, can you test if selecting another audio device is working when you play a SID tune in ACID64?

Did you test sid-device on another machine as well? I'm curious if the problem is specific to your machine or to something in your settings that you use which can cause the problem.

Are you able to connect an external audio device to your machine? Perhaps connect a Bluetooth head phone? It would be interesting to know if that device is working fine on your machine so then we know it is specific to your current audio device.

**Comment by WilfredC64** [comment]
There is no further feedback from user dhry and the problem can't be reproduced. I've checked 16 and 24 bit output and different sample rates, different sound devices and machines and all is working fine. The issue can only be investigated further when more info is provided.

If the problem is still there, please report the issue with more info. This issue will be closed since there is no responds from the reporter.
